/*
* This file was generated by Generator.xtend 
* for the WireframeSketcher screen file screen1.screen
* at Fri, 26 Sep 2014 13:04:35 +0200
*/
package application

import java.util.HashMap
import javafx.event.ActionEvent
import javafx.scene.input.MouseEvent
import javafx.fxml.FXML
import javafx.scene.Node
import org.apache.commons.io.FilenameUtils
import javafx.scene.input.MouseButton

/* Generated */
class ScreenNavigatorControllerscreen1 extends AbstractNavigatorController {

	
	// Constructor
	new(Object controller, HashMap<Long, String> map) {
		super()
		_appController = controller as AppController
		
		initNavigatorMap
		println("ScreenNavigatorControllerscreen1 initialized.")
		
	}
	
	/* Generated */
	@FXML
	def handleMouseEvent2(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleActionEvent4(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent6(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent8(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent9(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent12(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent13(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleActionEvent14(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent18(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){	
			loadNewFXMLForScreen (event,  "screen2")
		}
	} 
	
	/* Generated */
	@FXML
	def handleMouseEvent20(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent24(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleActionEvent27(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent34(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	override def initNavigatorMap(){
		_navigatorMap = <Long, String>newHashMap
		_navigatorMap.put(18l, "screen2")

	}
	/* Generated */
	override getAppController() {
		_appController
	}
	
	/* Generated */
	override getNavigatorMap() {
		_navigatorMap
	}
	
	/* Generated */
	override getScreenName() {
		"screen1"
	}
}