/*
* This file was generated by Generator.xtend 
* for the WireframeSketcher file screen2.screen
* as part of the project "muniapp"
* at Mon, 13 Oct 2014 13:10:34 +0200
*/
package application

import java.util.HashMap
import javafx.event.ActionEvent
import javafx.scene.input.MouseEvent
import javafx.fxml.FXML
import javafx.scene.Node
import javafx.scene.input.MouseButton

/* Generated */
class ScreenNavigatorControllerscreen2 extends AbstractNavigatorController {

	
	// Constructor
	new(Object controller, HashMap<Long, String> map) {
		super()
		_appController = controller as AppController
		
		initNavigatorMap
		println("ScreenNavigatorControllerscreen2 initialized.")
		
	}
	
	/* Generated */
	@FXML
	def handleMouseEvent68(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleActionEvent69(ActionEvent event) {
			loadNewFXMLForScreen (event,  "screen1")
	} 
	
	/* Generated */
	@FXML
	def handleMouseEvent70(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleActionEvent71(ActionEvent event) {
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent74(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent75(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent76(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent77(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent78(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleActionEvent79(ActionEvent event) {
			loadNewFXMLForScreen (event,  "screen3")
	} 
	
	/* Generated */
	@FXML
	def handleMouseEvent80(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent81(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent82(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent83(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent84(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent85(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent86(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent87(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent88(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent90(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent91(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent94(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	@FXML
	def handleMouseEvent95(MouseEvent event) {
		if(event.button == MouseButton.PRIMARY){
			val resource = getResourceForScreenFile(screenName + ".screen")
			var id = getPropertyForNode(event.source as Node, "id") 
			if (id != null && id != PropertyResult.NO_SUCH_METHOD){
				resource.performActionForWidgetId(id as String)
			} 
			resource.evaluateRules
		}
		
	}
	/* Generated */
	override def initNavigatorMap(){
		_navigatorMap = <Long, String>newHashMap
		_navigatorMap.put(79l, "screen3")
		_navigatorMap.put(69l, "screen1")

	}
	/* Generated */
	override getAppController() {
		_appController
	}
	
	/* Generated */
	override getNavigatorMap() {
		_navigatorMap
	}
	
	/* Generated */
	override getScreenName() {
		"screen2"
	}
}